// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ADTApi.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// A collection of EventRoute objects.
    /// </summary>
    public partial class EventRouteCollection
    {
        /// <summary>
        /// Initializes a new instance of the EventRouteCollection class.
        /// </summary>
        public EventRouteCollection()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the EventRouteCollection class.
        /// </summary>
        /// <param name="value">The EventRoute objects.</param>
        /// <param name="nextLink">A URI to retrieve the next page of
        /// results.</param>
        public EventRouteCollection(IList<EventRoute> value = default(IList<EventRoute>), string nextLink = default(string))
        {
            Value = value;
            NextLink = nextLink;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the EventRoute objects.
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public IList<EventRoute> Value { get; set; }

        /// <summary>
        /// Gets or sets a URI to retrieve the next page of results.
        /// </summary>
        [JsonProperty(PropertyName = "nextLink")]
        public string NextLink { get; set; }

    }
}
