// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ADTApi.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// An incoming edge.
    /// </summary>
    public partial class IncomingEdge
    {
        /// <summary>
        /// Initializes a new instance of the IncomingEdge class.
        /// </summary>
        public IncomingEdge()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the IncomingEdge class.
        /// </summary>
        /// <param name="edgeId">A user-provided string representing the id of
        /// this edge, unique in the context of the source digital twin, i.e.
        /// sourceId + edgeId is unique in the context of the service.</param>
        /// <param name="sourceId">The id of the source digital twin.</param>
        /// <param name="relationship">The name of the relationship.</param>
        /// <param name="edgeLink">Link to the edge resource itself, to be used
        /// for deletion.</param>
        public IncomingEdge(string edgeId = default(string), string sourceId = default(string), string relationship = default(string), string edgeLink = default(string))
        {
            EdgeId = edgeId;
            SourceId = sourceId;
            Relationship = relationship;
            EdgeLink = edgeLink;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets a user-provided string representing the id of this
        /// edge, unique in the context of the source digital twin, i.e.
        /// sourceId + edgeId is unique in the context of the service.
        /// </summary>
        [JsonProperty(PropertyName = "$edgeId")]
        public string EdgeId { get; set; }

        /// <summary>
        /// Gets or sets the id of the source digital twin.
        /// </summary>
        [JsonProperty(PropertyName = "$sourceId")]
        public string SourceId { get; set; }

        /// <summary>
        /// Gets or sets the name of the relationship.
        /// </summary>
        [JsonProperty(PropertyName = "$relationship")]
        public string Relationship { get; set; }

        /// <summary>
        /// Gets or sets link to the edge resource itself, to be used for
        /// deletion.
        /// </summary>
        [JsonProperty(PropertyName = "$edgeLink")]
        public string EdgeLink { get; set; }

    }
}
