// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ADTApi
{
    using Microsoft.Rest;
    using Models;
    using Newtonsoft.Json;

    /// <summary>
    /// A service for managing and querying digital twins and digital twin
    /// models.
    /// </summary>
    public partial interface IAzureDigitalTwinsAPI : System.IDisposable
    {
        /// <summary>
        /// The base URI of the service.
        /// </summary>
        System.Uri BaseUri { get; set; }

        /// <summary>
        /// Gets or sets json serialization settings.
        /// </summary>
        JsonSerializerSettings SerializationSettings { get; }

        /// <summary>
        /// Gets or sets json deserialization settings.
        /// </summary>
        JsonSerializerSettings DeserializationSettings { get; }

        /// <summary>
        /// The requested API version.
        /// </summary>
        string ApiVersion { get; }

        /// <summary>
        /// Subscription credentials which uniquely identify client
        /// subscription.
        /// </summary>
        ServiceClientCredentials Credentials { get; }


        /// <summary>
        /// Gets the IModelsOperations.
        /// </summary>
        IModelsOperations Models { get; }

        /// <summary>
        /// Gets the IQuery.
        /// </summary>
        IQuery Query { get; }

        /// <summary>
        /// Gets the IDigitalTwins.
        /// </summary>
        IDigitalTwins DigitalTwins { get; }

        /// <summary>
        /// Gets the IEventRoutes.
        /// </summary>
        IEventRoutes EventRoutes { get; }

    }
}
